typography_spectrum: 0.24460043502040207
color:
  brandStrength: 0.9523458043113351
  lightness: 0.7305862798821181
  saturation: 0.5393824882339686
  rhythmicContrast: 0.0001832942944020033
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/4286ffac-f8a1-4d4a-90ff-b50cc12e9f09.jpg
layout_spectrum: 0.9097119187936187
analytics:
  google: null
author:
  name: ''
  email: mel@mcn.org
  url: 'http://melmckinney.com'
name: Mel McKinney
navigation:
  - name: Dead Duck
    id: 8a963b80-d750-4f57-b3ec-78f0d1d7875d
    type: content
  - name: Where There's Smoke
    id: 2f17b1e9-52f9-4f0a-a288-f12f6eb5a25d
    type: content
  - name: 'The Finn, The Twin, And The Inn'
    id: 561c35d9-da51-4faf-bdf7-56194a946408
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8fdd230c-7cb6-492b-b233-55b4df37d031.ico
title: mel@mcn.org
