layout_spectrum: 0.6204601731151342
typography_spectrum: 0.8212765033822507
color:
  brandStrength: 0.9029422705061734
  lightness: 0.06045721075497568
  saturation: 0.2578820716589689
  rhythmicContrast: 0.47647570609115064
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
author:
  name: ''
  email: mel@mcn.org
  url: 'http://melmckinney.ink'
name: Mel McKinney
navigation:
  - name: Dead Duck
    id: 8a963b80-d750-4f57-b3ec-78f0d1d7875d
    type: content
  - name: Where There's Smoke
    id: 2f17b1e9-52f9-4f0a-a288-f12f6eb5a25d
    type: content
  - name: 'The Finn, The Twin, And The Inn'
    id: 561c35d9-da51-4faf-bdf7-56194a946408
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8fdd230c-7cb6-492b-b233-55b4df37d031.ico
title: ''
